context:
  version: "0.35.0"

package:
  name: fclones
  version: ${{ version }}

source:
  url: https://github.com/pkolaczk/fclones/archive/v${{ version }}.tar.gz
  sha256: 9d8bb36076190f799f01470f80e64c6a1f15f0d938793f8f607a2544cdd6115a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - fclones --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Efficient Duplicate File Finder
  homepage: https://github.com/pkolaczk/fclones
  repository: https://github.com/pkolaczk/fclones

extra:
  recipe-maintainers:
    - danielnachun
